# Generated by Django 5.2.15 on 2026-06-24 04:10

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=15)),
                ('village_or_area', models.CharField(max_length=100)),
                ('buying_frequency_days', models.IntegerField(default=7)),
                ('default_rate_kati', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('default_rate_khadi', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='ProductStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(choices=[('KATI', 'Kati Supari'), ('KHADI', 'Khadi Supari')], max_length=10, unique=True)),
                ('available_stock_kg', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('product_type', models.CharField(choices=[('KATI', 'Kati Supari'), ('KHADI', 'Khadi Supari')], max_length=10)),
                ('quantity_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rate_per_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('payment_mode', models.CharField(choices=[('CASH', 'Cash'), ('CREDIT', 'Udhari'), ('PARTIAL', 'Partial (Thoda Cash)')], max_length=10)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('amount_due', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('promise_date', models.DateField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='dashboard.customer')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('amount_received', models.DecimalField(decimal_places=2, max_digits=10)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='dashboard.customer')),
            ],
        ),
    ]
