# Generated by Django 5.2.15 on 2026-06-28 16:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('KATI', 'Kati Supari'), ('KHADI', 'Khadi Supari')], max_length=10)),
                ('variety_name', models.CharField(default='Normal', max_length=50)),
                ('brand_name', models.CharField(default='No Brand', max_length=50)),
                ('available_stock_kg', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('avg_purchase_rate_per_kg', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
            options={
                'unique_together': {('category', 'variety_name', 'brand_name')},
            },
        ),
        migrations.DeleteModel(
            name='ProductStock',
        ),
        migrations.RemoveField(
            model_name='order',
            name='product_type',
        ),
        migrations.AlterField(
            model_name='customer',
            name='buying_frequency_days',
            field=models.IntegerField(default=15),
        ),
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='order',
            name='amount_due',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=12),
        ),
        migrations.AlterField(
            model_name='order',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.customer'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_mode',
            field=models.CharField(choices=[('CASH', 'Cash'), ('CREDIT', 'Udhari'), ('PARTIAL', 'Partial')], default='CASH', max_length=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=12),
        ),
        migrations.AlterField(
            model_name='paymentledger',
            name='amount_received',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='paymentledger',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.customer'),
        ),
        migrations.AddField(
            model_name='order',
            name='product_item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='dashboard.productinventory'),
        ),
    ]
